#!/usr/bin/env bash
# Configure Nginx so it redirects to another page

apt-get install -y nginx
nginx_conf="/etc/nginx/sites-available/default"
sed -i '/location \/ {/a \\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' "$nginx_conf"
service nginx restart
