#!/usr/bin/env bash
# Configure Nginx to ahve a custom 404 page

apt-get install -y nginx
nginx_conf="/etc/nginx/sites-available/default"
sed -i '/server {/a \\terror_page 404 /404_custom;\nlocation = /404_custom {\n\tinternal;\n\treturn 404 "Ceci n'\''est pas une page";\n}' "$nginx_conf"
service nginx restart
